# Importing Libraries

In [256]:
import numpy as np
import pandas as pd
import ast

In [257]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [258]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

# Overviewing data

In [259]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

# Merging the data sets

In [260]:
movies = movies.merge(credits,on = 'title')

In [261]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

# Data Cleaning

*Items to be kept(Keeping in mind that we have to create tags)*
1. Generes
2. ID
3. Keywords
4. title(remove original title)
5. Overview
6. cast
7. crew

In [262]:
movies = movies[['id','title','overview','genres','keywords','cast','crew']]

In [263]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [264]:
movies.isnull().sum()

id          0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [265]:
movies.dropna(inplace = True)

In [266]:
movies.duplicated().sum()

0

In [267]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [268]:
#we have to use literal_eval function from ast module as the genres are in the form of string and has to be converted to list
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [269]:
movies['genres'] = movies['genres'].apply(convert)

In [270]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [271]:
#doing the same step for keywords 
movies['keywords'] = movies['keywords'].apply(convert)

In [272]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [273]:
#taking out only important characters from cast 
def convert3(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter !=3:
            L.append(i['name'])
            counter +=1
        else:
            break
    return L

In [274]:
movies['cast'] = movies['cast'].apply(convert3)

In [275]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [276]:
movies['crew']

0       [{"credit_id": "52fe48009251416c750aca23", "de...
1       [{"credit_id": "52fe4232c3a36847f800b579", "de...
2       [{"credit_id": "54805967c3a36829b5002c41", "de...
3       [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4       [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
                              ...
4804    [{"credit_id": "52fe44eec3a36847f80b280b", "de...
4805    [{"credit_id": "52fe487dc3a368484e0fb013", "de...
4806    [{"credit_id": "52fe4df3c3a36847f8275ecf", "de...
4807    [{"credit_id": "52fe4ad9c3a368484e16a36b", "de...
4808    [{"credit_id": "58ce021b9251415a390165d9", "de...
Name: crew, Length: 4806, dtype: object

In [277]:
def fetch_director(obj):
    if obj is None or obj == []:
        return []  # Return an empty list if obj is None or empty
        
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [278]:
movies['crew']= movies['crew'].apply(fetch_director)

In [279]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [280]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [281]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [284]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [285]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [290]:
movies.head()

,id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [287]:
movies['tags'][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 'Action',
 'Adventure',
 'Fantasy',
 'ScienceFiction',
 'cultureclash',
 'future',
 'spacewar',
 'spacecolony',
 'society',
 'spacetravel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alienplanet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'loveaffair',
 'antiwar',
 'powerrelations',
 'mindandsoul',
 '3d',
 'SamWorthington',
 'ZoeSaldana',
 'SigourneyWeaver',
 'JamesCameron']

In [291]:
new_df = movies[['id','title','tags']]

In [293]:
new_df.head()

,id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [297]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\Prathmesh\AppData\Local\Temp\ipykernel_15996\487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [298]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [300]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\Prathmesh\AppData\Local\Temp\ipykernel_15996\4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [301]:
new_df.head()

,id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [303]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [302]:
new_df['tags'][1]

"captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. adventure fantasy action ocean drugabuse exoticisland eastindiatradingcompany loveofone'slife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger johnnydepp orlandobloom keiraknightley goreverbinski"

In [333]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000,stop_words = 'english')

In [345]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [344]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [335]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [336]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [337]:
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [338]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
        
    return " ".join(y)

In [339]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\Prathmesh\AppData\Local\Temp\ipykernel_15996\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [ ]:
#calculating the cosine distance(angular) between vectors
#because euclidian distance is not a good measure for the high dimensional data (here 5000)
# hence use cosine distance

In [347]:
from sklearn.metrics.pairwise import cosine_similarity

In [350]:
#distance of each movie with one another
cosine_similarity(vectors)

array([[1.        , 0.08458258, 0.08718573, ..., 0.04559608, 0.        ,
        0.        ],
       [0.08458258, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
        0.02615329],
       [0.08718573, 0.06063391, 1.        , ..., 0.02451452, 0.        ,
        0.        ],
       ...,
       [0.04559608, 0.02378257, 0.02451452, ..., 1.        , 0.03962144,
        0.04229549],
       [0.        , 0.        , 0.        , ..., 0.03962144, 1.        ,
        0.08714204],
       [0.        , 0.02615329, 0.        , ..., 0.04229549, 0.08714204,
        1.        ]])

In [352]:
similarity = cosine_similarity(vectors)

In [372]:
sorted(list(enumerate(similarity[0])),reverse = True, key = lambda x:x[1])[1:6] # value of similarity with itself is 1
#diagonal elements of this similarity matrix will be 1

[(1216, 0.29061909685954823),
 (3730, 0.26401000024165),
 (507, 0.25903973506580724),
 (539, 0.2537477434955704),
 (2409, 0.2507061052819501)]

In [367]:
sorted(similarity[0],reverse=True)

[1.0,
 0.29061909685954823,
 0.26401000024165,
 0.25903973506580724,
 0.2537477434955704,
 0.2507061052819501,
 0.2484013136974297,
 0.24784079854830485,
 0.23995690956687132,
 0.23490461932490855,
 0.2348556961505104,
 0.23089735286521348,
 0.22830583024432843,
 0.22147019900891643,
 0.21524880100025257,
 0.21369687880543226,
 0.213352298825066,
 0.2092457497388747,
 0.20712325533373332,
 0.20668850837512243,
 0.2056773510573183,
 0.2056773510573183,
 0.20549873413169661,
 0.20518233866439894,
 0.20475971753873348,
 0.20056488422556012,
 0.20032733246124987,
 0.20032733246124987,
 0.199363055707225,
 0.19510570275964212,
 0.19391446622548786,
 0.19344776406574832,
 0.19344776406574832,
 0.1926263261127128,
 0.19184045508446734,
 0.18983159915049982,
 0.1898315991504998,
 0.1894422005883515,
 0.18857857160117855,
 0.18641092980036,
 0.18641092980036,
 0.18427434427242972,
 0.18316875326179907,
 0.18065550087085797,
 0.18009006755629928,
 0.17937400083354382,
 0.17937400083354382,
 0.17757120130114434,
 0.17757120130114434,
 0.17757120130114434,
 0.17757120130114434,
 0.1771615786072478,
 0.1754942736973651,
 0.1752499093081954,
 0.17348855898381338,
 0.17348855898381338,
 0.17170914210964275,
 0.17122340098907804,
 0.1696751579473019,
 0.1696751579473019,
 0.16916516233038026,
 0.16839306718964578,
 0.1678603981989089,
 0.16673100431301852,
 0.16646698038757363,
 0.1643989873053573,
 0.1643989873053573,
 0.1633934794796094,
 0.162746694241347,
 0.16120647005479025,
 0.1600142241187995,
 0.15949044456578,
 0.15819299929208316,
 0.15719549837837185,
 0.15608456220771372,
 0.1559625734730109,
 0.1559625734730109,
 0.15404884978892908,
 0.15220388682955233,
 0.1522038868295523,
 0.1522038868295523,
 0.15007505629691606,
 0.1487044791289829,
 0.1487044791289829,
 0.1487044791289829,
 0.14856672599230308,
 0.14797064923339878,
 0.14763464883937316,
 0.14704292441876157,
 0.14704292441876157,
 0.14704292441876154,
 0.14615084586538157,
 0.14615084586538157,
 0.1454358496691159,
 0.14543584966911588,
 0.1453095484297741,
 0.1453095484297741,
 0.1453095484297741,
 0.1438803413133505,
 0.1438803413133505,
 0.14349920066683505,
 0.14349920066683505,
 0.14309095175803563,
 0.14309095175803563,
 0.1430909517580356,
 0.14237369936287486,
 0.14165281524036175,
 0.14097096860865022,
 0.14097096860865022,
 0.14097096860865022,
 0.14059173052284343,
 0.14019992744655632,
 0.14019992744655632,
 0.14019992744655632,
 0.14019992744655632,
 0.1389425035941821,
 0.1389425035941821,
 0.1389425035941821,
 0.13812277665483924,
 0.1371182340382122,
 0.1371182340382122,
 0.1371182340382122,
 0.1371182340382122,
 0.1371182340382122,
 0.13699915608779772,
 0.13699915608779772,
 0.13678822577626598,
 0.13657399193174952,
 0.1354916256531435,
 0.1354916256531435,
 0.1354916256531435,
 0.13513513513513514,
 0.13513513513513514,
 0.1342312110428049,
 0.1342312110428049,
 0.1342312110428049,
 0.13334518676566626,
 0.13334518676566626,
 0.13300532955644181,
 0.1316245316231641,
 0.1316245316231641,
 0.1316245316231641,
 0.13151918984428584,
 0.13151918984428584,
 0.13151918984428584,
 0.13065106689280268,
 0.12996881122750908,
 0.12996881122750908,
 0.12996881122750908,
 0.12996881122750908,
 0.12996881122750908,
 0.1289651760438322,
 0.1289651760438322,
 0.1289651760438322,
 0.1283740414907742,
 0.1283740414907742,
 0.12734290799340264,
 0.12734290799340264,
 0.12683657235796025,
 0.12683657235796025,
 0.12683657235796025,
 0.12683657235796025,
 0.12655439943366653,
 0.12655439943366653,
 0.12655439943366653,
 0.12629480039223434,
 0.12527215359889848,
 0.12427395320024,
 0.12427395320024,
 0.12427395320023998,
 0.12392039927415242,
 0.12392039927415242,
 0.12392039927415242,
 0.12329924047901797,
 0.12329924047901797,
 0.12329924047901797,
 0.12329924047901797,
 0.1221125021745327,
 0.1221125021745327,
 0.1221125021745327,
 0.1221125021745327,
 0.1221125021745327,
 0.1221125021745327,
 0.12141669877745292,
 0.12141669877745292,
 0.12119654139092992,
 0.1211965413909299,
 0.1211965413909299,
 0.12006004503753284,
 0.12006004503753284,
 0.12006004503753284,
 0.12006004503753284,
 0.12006004503753284,
 0.11990028442779209,
 0.11961783342433499,
 0.11961783342433499,
 0.11961783342433499,
 0.11961783342433499,
 0.11869522585912262,
 0.1186447494690624,
 0.1186447494690624,
 0.1186447494690624,
 0.1186447494690624,
 0.11810771907149853,
 0.11810771907149853,
 0.1178966237837789,
 0.11742784807525519,
 0.11742784807525519,
 0.11706342165578529,
 0.1166080974034697,
 0.1162476387438193,
 0.11624763874381928,
 0.11624763874381928,
 0.11624763874381927,
 0.11624763874381927,
 0.11624763874381927,
 0.11624763874381927,
 0.11565903932254226,
 0.11510231387903269,
 0.1144727614064285,
 0.1144727614064285,
 0.11399018814688831,
 0.1139901881468883,
 0.1139901881468883,
 0.11394547734377711,
 0.11389895949029985,
 0.11314714296070713,
 0.11314714296070713,
 0.11314714296070713,
 0.11314714296070713,
 0.11290968804428624,
 0.11290968804428622,
 0.11277677488692017,
 0.11277677488692017,
 0.11277677488692017,
 0.11277677488692017,
 0.11241002017619531,
 0.11241002017619531,
 0.11185934253567072,
 0.11168711865749101,
 0.11168711865749101,
 0.11115400287534569,
 0.11115400287534567,
 0.11115400287534567,
 0.11115400287534567,
 0.11115400287534567,
 0.11115400287534567,
 0.11083777463036817,
 0.11083777463036817,
 0.11028219331407116,
 0.11028219331407116,
 0.11028219331407116,
 0.11028219331407116,
 0.11022596991336672,
 0.10984369379093671,
 0.1098436937909367,
 0.1098436937909367,
 0.1098436937909367,
 0.1098436937909367,
 0.10959932487023819,
 0.10959932487023819,
 0.10959932487023819,
 0.10892898631973956,
 0.10887588907733554,
 0.10827079910776224,
 0.10810810810810811,
 0.10810810810810811,
 0.10793322294408637,
 0.10793322294408637,
 0.10762440050012628,
 0.10762440050012628,
 0.10762440050012628,
 0.10762440050012628,
 0.10762440050012628,
 0.10762440050012628,
 0.10701462561817378,
 0.10701462561817378,
 0.10701462561817376,
 0.106676149412533,
 0.106676149412533,
 0.106676149412533,
 0.106676149412533,
 0.1061190899945022,
 0.10529962529853128,
 0.10529962529853128,
 0.10529962529853128,
 0.10529962529853128,
 0.10529962529853128,
 0.10529962529853128,
 0.10529962529853128,
 0.10529962529853128,
 0.10524566699352861,
 0.10524566699352861,
 0.10514994558491725,
 0.10514994558491725,
 0.10514994558491725,
 0.10514994558491725,
 0.10514994558491725,
 0.10514994558491725,
 0.10514994558491723,
 0.10514994558491723,
 0.10439346133241542,
 0.10397504898200727,
 0.10397504898200727,
 0.10397504898200727,
 0.10397504898200727,
 0.10397504898200727,
 0.10397504898200727,
 0.10397504898200727,
 0.10397504898200727,
 0.10356162766686666,
 0.10283867552865913,
 0.10283867552865913,
 0.10283867552865913,
 0.10269923319261937,
 0.10269923319261937,
 0.10269923319261937,
 0.10195592378577323,
 0.10195592378577323,
 0.1019559237857732,
 0.10146925788636821,
 0.10146925788636821,
 0.10146925788636821,
 0.10146925788636821,
 0.10146925788636821,
 0.10146925788636821,
 0.1011805823145441,
 0.1011805823145441,
 0.10067340828210367,
 0.10067340828210367,
 0.10067340828210367,
 0.10067340828210367,
 0.10067340828210367,
 0.10067340828210367,
 0.10067340828210367,
 0.10067340828210367,
 0.10067340828210367,
 0.10067340828210367,
 0.10067340828210367,
 0.10042266465917388,
 0.10028244211278005,
 0.10028244211278005,
 0.10028244211278005,
 0.10028244211278005,
 0.10028244211278005,
 0.10028244211278005,
 0.09968152785361249,
 0.09913631941932194,
 0.09913631941932194,
 0.09913631941932194,
 0.09913631941932194,
 0.09913631941932194,
 0.09913631941932194,
 0.09913631941932194,
 0.09913631941932194,
 0.09863939238321438,
 0.09863939238321438,
 0.09863939238321438,
 0.09863939238321438,
 0.09863939238321438,
 0.09863939238321438,
 0.09863939238321438,
 0.09863939238321438,
 0.09863939238321438,
 0.09863939238321438,
 0.09863939238321438,
 0.09863939238321438,
 0.09802861627917438,
 0.09802861627917438,
 0.09695723311274393,
 0.09695723311274393,
 0.09695723311274393,
 0.09695723311274393,
 0.09672388203287416,
 0.09672388203287416,
 0.09672388203287416,
 0.09672388203287416,
 0.09672388203287416,
 0.09620723036050562,
 0.09620723036050562,
 0.09592022754223367,
 0.09491579957524991,
 0.09491579957524991,
 0.09491579957524991,
 0.09491579957524991,
 0.09491579957524991,
 0.09491579957524991,
 0.09491579957524991,
 0.09491579957524991,
 0.09491579957524991,
 0.0949157995752499,
 0.0949157995752499,
 0.0949157995752499,
 0.0949157995752499,
 0.0949157995752499,
 0.0949157995752499,
 0.0949157995752499,
 0.0949157995752499,
 0.0949157995752499,
 0.09491579957524988,
 0.09394227846020416,
 0.09394227846020416,
 0.09394227846020416,
 0.09394227846020416,
 0.09394227846020416,
 0.09394227846020416,
 0.09394227846020416,
 0.09394227846020416,
 0.09367501681349609,
 0.09320546490018,
 0.09320546490018,
 0.09320546490018,
 0.09320546490018,
 0.09320546490018,
 0.09320546490018,
 0.09320546490018,
 0.09320546490018,
 0.09320546490018,
 0.0930725988812425,
 0.0930725988812425,
 0.09248165577087425,
 0.09248165577087424,
 0.09208185110322616,
 0.09208185110322616,
 0.09208185110322616,
 0.09208185110322616,
 0.09208185110322616,
 0.09158437663089954,
 0.09158437663089954,
 0.09158437663089952,
 0.09158437663089952,
 0.09158437663089952,
 0.09158437663089952,
 0.09158437663089952,
 0.09158437663089952,
 0.09119215051751065,
 0.09119215051751065,
 0.09119215051751065,
 0.09119215051751065,
 0.09119215051751065,
 0.09119215051751065,
 0.09119215051751065,
 0.09119215051751065,
 0.09097816785925636,
 0.09032775043542898,
 0.0902256659231352,
 0.09004503377814962,
 0.09004503377814962,
 0.09004503377814962,
 0.09004503377814962,
 0.09004503377814962,
 0.09004503377814962,
 0.09004503377814962,
 0.08948747402853657,
 0.08948747402853657,
 0.08948747402853657,
 0.08948747402853657,
 0.08948747402853657,
 0.08948747402853657,
 0.08948747402853657,
 0.08948747402853657,
 0.0891578689526865,
 0.08867021970429453,
 0.08867021970429453,
 0.08867021970429453,
 0.0886379935648677,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.08787495503274936,
 0.08787495503274936,
 0.08787495503274936,
 0.08787495503274936,
 0.08787495503274936,
 0.08787495503274936,
 0.08787495503274936,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.08710071126186844,
 0.08710071126186844,
 0.08710071126186844,
 0.0863465783552691,
 0.0863465783552691,
 0.08585457105482137,
 0.08585457105482137,
 0.08585457105482137,
 0.08585457105482137,
 0.08585457105482137,
 0.08585457105482136,
 0.08561170049453902,
 0.08561170049453902,
 0.08561170049453902,
 0.08561170049453902,
 0.08489527199560176,
 0.08489527199560176,
 0.08489527199560176,
 0.08489527199560176,
 0.08489527199560176,
 0.08489527199560176,
 0.08489527199560176,
 0.08489527199560176,
 0.08489527199560176,
 0.08489527199560176,
 0.08458258116519013,
 0.08458258116519013,
 0.08458258116519013,
 0.08458258116519013,
 0.08458258116519013,
 0.08458258116519013,
 0.08458258116519013,
 0.08433490104000933,
 0.08419653359482289,
 0.08419653359482289,
 0.08419653359482289,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08284930213349333,
 0.08284930213349333,
 0.08284930213349333,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08108108108108109,
 0.08108108108108109,
 0.08108108108108109,
 0.08108108108108109,
 0.08108108108108109,
 0.08108108108108109,
 0.08108108108108109,
 0.08108108108108109,
 0.08099356774626426,
 0.08094446585163528,
 0.08094446585163528,
 0.08094446585163528,
 0.08094446585163528,
 0.0803381317273391,
 0.0803381317273391,
 0.0803381317273391,
 0.0803381317273391,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.07983920607777244,
 0.07974522228289,
 0.07974522228289,
 0.07974522228289,
 0.07974522228289,
 0.07974522228289,
 0.07974522228289,
 0.07974522228289,
 0.07974522228289,
 0.07974522228289,
 0.07916524933276792,
 0.07897471897389846,
 0.07897471897389846,
 0.07897471897389846,
 0.07897471897389846,
 0.07897471897389846,
 0.07897471897389846,
 0.07897471897389846,
 0.07897471897389846,
 0.07897471897389846,
 0.07859774918918593,
 0.07859774918918593,
 0.07804228110385686,
 0.07798128673650545,
 0.07798128673650545,
 0.07798128673650545,
 0.07798128673650545,
 0.07798128673650545,
 0.07798128673650545,
 0.07798128673650545,
 0.07798128673650545,
 0.07798128673650545,
 0.07798128673650545,
 0.07798128673650545,
 0.07798128673650545,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07726033486461518,
 0.07702442489446452,
 0.07702442489446452,
 0.07702442489446452,
 0.07702442489446452,
 0.07702442489446452,
 0.07702442489446452,
 0.07702442489446452,
 0.07702442489446452,
 0.07702442489446452,
 0.07702442489446452,
 0.07696578428840449,
 0.07696578428840449,
 0.07632031385908294,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477615,
 0.0759326396601999,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07521183158458504,
 0.07521183158458504,
 0.07521183158458504,
 0.07521183158458504,
 0.07521183158458504,
 0.07521183158458504,
 0.07494001345079687,
 0.07494001345079687,
 0.07494001345079687,
 0.074458079104994,
 0.074458079104994,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07398532461669939,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07306621658015879,
 0.07271792483455794,
 0.07271792483455794,
 0.07271792483455794,
 0.07271792483455794,
 0.07271792483455794,
 0.07271792483455794,
 0.07271792483455794,
 0.07271792483455794,
 0.07271792483455794,
 0.07271792483455794,
 0.07271792483455794,
 0.07271792483455794,
 0.07218053273850816,
 0.07194017065667525,
 0.07194017065667525,
 0.07194017065667525,
 0.07194017065667525,
 0.07194017065667525,
 0.07194017065667525,
 0.07194017065667525,
 0.07194017065667525,
 0.07194017065667525,
 0.07194017065667525,
 0.07194017065667525,
 0.07194017065667525,
 0.07174960033341753,
 0.07174960033341753,
 0.07174960033341753,
 0.07174960033341753,
 0.07174960033341753,
 0.07174960033341753,
 0.07174960033341753,
 0.0713262951621492,
 0.0713262951621492,
 0.07118684968143743,
 0.07118684968143743,
 0.07118684968143743,
 0.07118684968143743,
 0.07118684968143743,
 0.07045670884515312,
 0.07045670884515312,
 0.07045670884515312,
 0.07045670884515312,
 0.07045670884515312,
 0.07045670884515312,
 0.07045670884515312,
 0.07045670884515312,
 0.07045670884515312,
 0.07045670884515312,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.06974858324629157,
 0.06974858324629157,
 0.06974858324629157,
 0.06974858324629157,
 0.06974858324629157,
 0.06974858324629157,
 0.06974858324629157,
 0.06906138832741962,
 0.06906138832741962,
 0.06906138832741962,
 0.06906138832741962,
 0.06906138832741962,
 0.06906138832741962,
 0.06906138832741962,
 0.06906138832741962,
 0.06906138832741962,
 0.06906138832741962,
 0.06906138832741962,
 0.06906138832741962,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.06839411288813299,
 0.06839411288813299,
 0.06839411288813299,
 0.06839411288813299,
 0.06839411288813299,
 0.06839411288813299,
 0.06839411288813299,
 0.06774581282657174,
 0.06774581282657174,
 0.06774581282657174,
 0.06774581282657174,
 0.06774581282657174,
 0.06746792083200746,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140243,
 0.06711560552140243,
 0.06711560552140243,
 0.06711560552140243,
 0.06711560552140243,
 0.06711560552140243,
 0.06711560552140243,
 0.06676875252493802,
 0.06676875252493802,
 0.06667259338283313,
 0.0665026647782209,
 0.0665026647782209,
 0.0665026647782209,
 0.0665026647782209,
 0.0665026647782209,
 0.0665026647782209,
 0.0665026647782209,
 0.0665026647782209,
 0.0664272221393253,
 0.06609087961288129,
 0.06590621627456203,
 0.06590621627456203,
 0.06590621627456203,
 0.06590621627456203,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06532553344640132,
 0.06532553344640132,
 0.06532553344640132,
 0.06532553344640132,
 0.06532553344640132,
 0.06532553344640132,
 0.06532553344640132,
 0.06475993376645182,
 0.06475993376645182,
 0.06475993376645182,
 0.06475993376645182,
 0.06475993376645182,
 0.06475993376645182,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,

In [384]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie ].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse = True, key = lambda x:x[1])[1:6]
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [385]:
recommend('Batman Begins')

The Dark Knight
Batman
Batman
The Dark Knight Rises
10th & Wolf

In [393]:
import pickle

In [396]:
pickle.dump(new_df,open('movie_dict.pkl','wb'))

In [397]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [398]:
pickle.dump(similarity,open('similarity.pkl','wb'))